# Site settings
title: meiwenzi
description: meiwenzi
favicon: /assets/img/head_pic.jpg
baseurl:
url: https://meiwenzi.github.io
rss_url:

# Build settings

highlight: true
#highlighter: rouge

timezone: Asia/Shanghai

# kramdown是markdown的超集,在Jekyll中支持, 可以用于Github搭建博客. 
# 和Jekyll一样, 使用Ruby作为核心语言. 由于Maruku不再更新, Github推荐使用kramdown作为markdown解析. 
# kramdown作为markdown解析器号称速度快, 比PHP markdown和Maruku都要快几倍.
markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style
